In [1]:
!pip install torch


[notice] A new release of pip is available: 23.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import torch

var1 = torch.tensor(5)
print(var1)
print(var1.shape)

# tensor(5)
# torch.Size([])

tensor(5)
torch.Size([])


In [ ]:
var2 = torch.tensor([10])
print(var2)
print(var2.shape)
# tensor([10])
# torch.Size([1])

tensor([10])
torch.Size([1])


In [ ]:
var3 = torch.tensor(3)
result = var1 + var3
print(result)
# tensor(8)
print(result.item())
# 8

tensor(8)
8


In [22]:
var1 = torch.tensor([1, 2, 3])
print(var1)         # tensor([1, 2, 3])
print(var1.shape)   # torch.Size([3])

tensor([1, 2, 3])
torch.Size([3])


In [ ]:
var2 = var1 + 10
print(var2)       # tensor([11, 12, 13])
var3 = var1 * 2
print(var3)       # tensor([2, 4, 6])

tensor([11, 12, 13])


In [ ]:
var4  = torch.tensor([1,2,3])
result = var1 @ var4 
result      # tensor(14)

tensor(14)

In [14]:
var1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
var2 = torch.tensor([[10, 20, 30], [40, 50, 60]])
print(var1)     # tensor([[1, 2, 3],
                #         [4, 5, 6]])
print(var1.shape)  # torch.Size([2, 3])

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [16]:
print(var1 + var2)  # tensor([[11, 22, 33],
                    #         [44, 55, 66]])
print(var1 * var2)  # tensor([[ 10,  40,  90],
                    #         [160, 250, 360]])

tensor([[11, 22, 33],
        [44, 55, 66]])
tensor([[ 10,  40,  90],
        [160, 250, 360]])


In [ ]:
var3 = torch.tensor([[1,2],[2,4], [3,4,]])
print(torch.mm(var1, var3))     # tensor([[ 20,  40],
                                #         [ 56, 112]])
print(var1 @ var3)      # tensor([[ 20,  40],
                        #         [ 56, 112]])

tensor([[14, 22],
        [32, 52]])
tensor([[14, 22],
        [32, 52]])


In [ ]:
var1 = torch.tensor([
    [[1, 2],[3, 4]],
    [[5, 6],[7, 8]]
])
var2 = torch.tensor([
    [[10, 20],[30, 40]],
    [[50, 60],[70, 80]]
])

print(var1)     # tensor([[[1, 2],
                #          [3, 4]],
                #
                #         [[5, 6],
                #          [7, 8]]])
print(var1.shape)  # torch.Size([2, 2, 2])

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])


In [26]:
data = [
    [1,2],
    [3,4]
]
t1 = torch.tensor(data)
print(t1)   # tensor([[1, 2],
            #         [3, 4]])

tensor([[1, 2],
        [3, 4]])


In [27]:
t1 = torch.tensor([5])
t2 = torch.tensor([10])
ndarr1 = (t1 + t2).numpy()
print(ndarr1)   # [15]
print(type(ndarr1)) # <class 'numpy.ndarray'>

[15]
<class 'numpy.ndarray'>


In [29]:
result = ndarr1 * 10
t3 = torch.from_numpy(result)
print(t3)  # tensor([150])
print(type(t3))  # <class 'torch.Tensor'>

tensor([150])
<class 'torch.Tensor'>


In [ ]:
t1 = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(t1[0])        # tensor([1, 2, 3, 4])
print(t1[:, 0])     # tensor([1, 5, 9])
print(t1[:, -1])    # tensor([ 4,  8, 12])
print(t1[..., 2])   # tensor([ 3,  7, 11])


tensor([1, 2, 3, 4])
tensor([1, 5, 9])
tensor([ 4,  8, 12])
tensor([ 3,  7, 11])
