In [2]:
import pandas as pd

idx = ['김사과', '반하나', '오렌지', '이메론', '배애리']
data = [67, 75, 90, 62, 98]

# pd.Series(데이터, 인덱스, ...)
pd.Series(data)

# 0    67
# 1    75
# 2    90
# 3    62
# 4    98
# dtype: int64

ModuleNotFoundError: No module named 'pandas'

In [ ]:
se1 = pd.Series(data, idx)
se1

# 김사과    67
# 반하나    75
# 오렌지    90
# 이메론    62
# 배애리    98
# dtype: int64

김사과    67
반하나    75
오렌지    90
이메론    62
배애리    98
dtype: int64

In [ ]:
print(se1.index)
print(se1.values)
print(type(se1.values))

# Index(['김사과', '반하나', '오렌지', '이메론', '배애리'], dtype='object')
# [67 75 90 62 98]
# <class 'numpy.ndarray'>

Index(['김사과', '반하나', '오렌지', '이메론', '배애리'], dtype='object')
[67 75 90 62 98]
<class 'numpy.ndarray'>


In [ ]:
data = [[67, 93, 91],
        [75, 68, 96],
        [87, 81, 82],
        [62, 70, 75],
        [98, 56, 87]]

idx = ['김사과', '반하나', '오렌지', '이메론', '배애리']
col = ['국어', '영어', '수학']

In [ ]:
# pd.DataFrame(데이터, 인덱스, 컬럼, ...)
pd.DataFrame(data)

0   1   2
0  67  93  91
1  75  68  96
2  87  81  82
3  62  70  75
4  98  56  87

In [ ]:
se1.values

array([67, 75, 90, 62, 98])

In [ ]:
pd.DataFrame(data, idx)

0   1   2
김사과  67  93  91
반하나  75  68  96
오렌지  87  81  82
이메론  62  70  75
배애리  98  56  87

In [ ]:
pd.DataFrame(data, idx, col)

국어  영어  수학
김사과  67  93  91
반하나  75  68  96
오렌지  87  81  82
이메론  62  70  75
배애리  98  56  87

In [ ]:
df = pd.DataFrame(index=idx, columns=col, data=data)
df

국어  영어  수학
김사과  67  93  91
반하나  75  68  96
오렌지  87  81  82
이메론  62  70  75
배애리  98  56  87

In [ ]:
print(df.index)
print(df.columns)
print(df.values)

# Index(['김사과', '반하나', '오렌지', '이메론', '배애리'], dtype='object')
# Index(['국어', '영어', '수학'], dtype='object')
# [[67 93 91]
#  [75 68 96]
#  [87 81 82]
#  [62 70 75]
#  [98 56 87]]

Index(['김사과', '반하나', '오렌지', '이메론', '배애리'], dtype='object')
Index(['국어', '영어', '수학'], dtype='object')
[[67 93 91]
 [75 68 96]
 [87 81 82]
 [62 70 75]
 [98 56 87]]


In [ ]:
df = pd.read_csv("idol.csv")

In [ ]:
df

이름     그룹   소속사  성별        생년월일      키  혈액형  브랜드평판지수
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.info()

# <class 'pandas.core.frame.DataFrame'>
# RangeIndex: 20 entries, 0 to 19
# Data columns (total 8 columns):
#  #   Column   Non-Null Count  Dtype  
# ---  ------   --------------  -----  
#  0   이름       20 non-null     object 
#  1   그룹       20 non-null     object 
#  2   소속사      19 non-null     object 
#  3   성별       20 non-null     object 
#  4   생년월일     20 non-null     object 
#  5   키        19 non-null     float64
#  6   혈액형      19 non-null     object 
#  7   브랜드평판지수  20 non-null     int64  
# dtypes: float64(1), int64(1), object(6)
# memory usage: 1.4+ KB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   이름       20 non-null     object 
 1   그룹       20 non-null     object 
 2   소속사      19 non-null     object 
 3   성별       20 non-null     object 
 4   생년월일     20 non-null     object 
 5   키        19 non-null     float64
 6   혈액형      19 non-null     object 
 7   브랜드평판지수  20 non-null     int64  
dtypes: float64(1), int64(1), object(6)
memory usage: 1.4+ KB


In [ ]:
df.columns

# Index(['이름', '그룹', '소속사', '성별', '생년월일', '키', '혈액형', '브랜드평판지수'], dtype='object')

Index(['이름', '그룹', '소속사', '성별', '생년월일', '키', '혈액형', '브랜드평판지수'], dtype='object')

In [ ]:
new_columns = ['name', 'group', 'company', 'gender', 'birthday', 'height', 'blood', 'brand']
df.columns = new_columns
df

name  group company gender    birthday  height blood    brand
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587

In [ ]:
# describe(): 통계 정보를 반환
df.describe()

height         brand
count   19.000000  2.000000e+01
mean   170.536842  2.700190e+06
std      7.225204  1.381919e+06
min    161.000000  1.680587e+06
25%    164.750000  1.887423e+06
50%    168.000000  2.074682e+06
75%    179.000000  2.623465e+06
max    182.000000  6.267302e+06

In [ ]:
df.describe(include=object) # Top: 최빈값, freq: 최빈값의 빈도

name  group company gender    birthday blood
count    20     20      19     20          20    19
unique   20      6       5      2          20     4
top      지민  방탄소년단     빅히트     여자  1995-10-13     A
freq      1      5       7     13           1    11

In [ ]:
# 원하는 개수의 데이터 보기
df.head() # 상위 5개의 row를 출력

name  group company gender    birthday  height blood    brand
0   지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1   정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2   민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3   하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4    뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048

In [ ]:
df.tail() # 하위 2개의 row를 출력

name  group company gender    birthday  height blood    brand
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587

In [ ]:
# 정렬하기
df.sort_index() # index로 오름차순 정렬: 기본값

name  group company gender    birthday  height blood    brand
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587

In [ ]:
df['blood']

0       A
1       A
2       A
3       O
4      AB
5     NaN
6       O
7       A
8       B
9       A
10      A
11      B
12      A
13      A
14      B
15      B
16      A
17      A
18      A
19      O
Name: blood, dtype: object

In [ ]:
df['blood']

# 0       A
# 1       A
# 2       A
# 3       O
# 4      AB
# 5     NaN
# 6       O
# 7       A
# 8       B
# 9       A
# 10      A
# 11      B
# 12      A
# 13      A
# 14      B
# 15      B
# 16      A
# 17      A
# 18      A
# 19      O
# Name: blood, dtype: object

0       A
1       A
2       A
3       O
4      AB
5     NaN
6       O
7       A
8       B
9       A
10      A
11      B
12      A
13      A
14      B
15      B
16      A
17      A
18      A
19      O
Name: blood, dtype: object

In [ ]:
df[:3]

name  group company gender    birthday  height blood    brand
0   지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1   정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2   민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081

In [ ]:
# loc 인덱싱: 컬럼 인덱싱
df.loc[3:5, 'name'] # df['name']

# 3     하니
# 4      뷔
# 5    다니엘
# Name: name, dtype: object

3     하니
4      뷔
5    다니엘
Name: name, dtype: object

In [ ]:
df.loc[2:5, ['name', 'gender', 'height']]

name gender  height
2   민지     여자   169.0
3   하니     여자   161.7
4    뷔     남자   179.0
5  다니엘     여자   165.0

In [ ]:
df.loc[[2,5], ['name', 'gender', 'height']]

name gender  height
2   민지     여자   169.0
5  다니엘     여자   165.0

In [ ]:
df.loc[2:5, 'name':'gender']

name  group company gender
2   민지    뉴진스     어도어     여자
3   하니    뉴진스     어도어     여자
4    뷔  방탄소년단     빅히트     남자
5  다니엘    뉴진스     어도어     여자

In [ ]:
df.iloc[:, 0:3] # 3을 포함하지 않음

name  group company
0     지민  방탄소년단     빅히트
1     정국  방탄소년단     빅히트
2     민지    뉴진스     어도어
3     하니    뉴진스     어도어
4      뷔  방탄소년단     빅히트
5    다니엘    뉴진스     어도어
6     혜인    뉴진스     어도어
7     지수   블랙핑크     와이지
8     해린    뉴진스     어도어
9     태연   소녀시대     에스엠
10    RM  방탄소년단     빅히트
11    제니   블랙핑크     와이지
12   옹성우    워너원    판타지오
13    리사   블랙핑크     와이지
14    로제   블랙핑크     와이지
15    윤아   소녀시대     에스엠
16    조이   레드벨벳     빅히트
17    슬기   레드벨벳     빅히트
18  강다니엘    워너원     NaN
19     진  방탄소년단     빅히트

In [ ]:
df['height'] >= 180
# 0     False
# 1     False
# 2     False
# 3     False
# 4     False
# 5     False
# 6     False
# 7     False
# 8     False
# 9     False
# 10     True
# 11    False
# 12    False
# 13    False
# 14    False
# 15    False
# 16    False
# 17    False
# 18     True
# 19    False
# Name: height, dtype: bool

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18     True
19    False
Name: height, dtype: bool

In [ ]:
df[df['height'] >= 180]

name  group company gender    birthday  height blood    brand
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444

In [ ]:
df.loc[df['height'] >= 180, ['name', 'gender', 'height']]

name gender  height
10    RM     남자   181.0
18  강다니엘     남자   182.0

In [ ]:
df[df['height'] >= 180][['name', 'gender', 'height']]

name gender  height
10    RM     남자   181.0
18  강다니엘     남자   182.0

In [ ]:
company = [ '어도어']
df['company'].isin(company)

# 0     False
# 1     False
# 2      True
# 3      True
# 4     False
# 5      True
# 6      True
# 7     False
# 8      True
# 9     False
# 10    False
# 11    False
# 12    False
# 13    False
# 14    False
# 15    False
# 16    False
# 17    False
# 18    False
# 19    False
# Name: company, dtype: bool

0     False
1     False
2      True
3      True
4     False
5      True
6      True
7     False
8      True
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: company, dtype: bool

In [ ]:
df[df['company'].isin(company)]# df.loc[df['company'].isin(company),:]

name group company gender    birthday  height blood    brand
2   민지   뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3   하니   뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
5  다니엘   뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
6   혜인   뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
8   해린   뉴진스     어도어     여자  2006-05-15   164.5     B  2173376

In [ ]:
df.info()

# <class 'pandas.core.frame.DataFrame'>
# RangeIndex: 20 entries, 0 to 19
# Data columns (total 8 columns):
#  #   Column    Non-Null Count  Dtype  
# ---  ------    --------------  -----  
#  0   name      20 non-null     object 
#  1   group     20 non-null     object 
#  2   company   19 non-null     object 
#  3   gender    20 non-null     object 
#  4   birthday  20 non-null     object 
#  5   height    19 non-null     float64
#  6   blood     19 non-null     object 
#  7   brand     20 non-null     int64  
# dtypes: float64(1), int64(1), object(6)
# memory usage: 1.4+ KB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      20 non-null     object 
 1   group     20 non-null     object 
 2   company   19 non-null     object 
 3   gender    20 non-null     object 
 4   birthday  20 non-null     object 
 5   height    19 non-null     float64
 6   blood     19 non-null     object 
 7   brand     20 non-null     int64  
dtypes: float64(1), int64(1), object(6)
memory usage: 1.4+ KB


In [ ]:
df.isna()

name  group  company  gender  birthday  height  blood  brand
0   False  False    False   False     False   False  False  False
1   False  False    False   False     False   False  False  False
2   False  False    False   False     False   False  False  False
3   False  False    False   False     False   False  False  False
4   False  False    False   False     False   False  False  False
5   False  False    False   False     False   False   True  False
6   False  False    False   False     False   False  False  False
7   False  False    False   False     False   False  False  False
8   False  False    False   False     False   False  False  False
9   False  False    False   False     False    True  False  False
10  False  False    False   False     False   False  False  False
11  False  False    False   False     False   False  False  False
12  False  False    False   False     False   False  False  False
13  False  False    False   False     False   False  False  False
14  False  False    False   False     False   False  False  False
15  False  False    False   False     False   False  False  False
16  False  False    False   False     False   False  False  False
17  False  False    False   False     False   False  False  False
18  False  False     True   False     False   False  False  False
19  False  False    False   False     False   False  False  False

In [ ]:
df.isnull()

name  group  company  gender  birthday  height  blood  brand
0   False  False    False   False     False   False  False  False
1   False  False    False   False     False   False  False  False
2   False  False    False   False     False   False  False  False
3   False  False    False   False     False   False  False  False
4   False  False    False   False     False   False  False  False
5   False  False    False   False     False   False   True  False
6   False  False    False   False     False   False  False  False
7   False  False    False   False     False   False  False  False
8   False  False    False   False     False   False  False  False
9   False  False    False   False     False    True  False  False
10  False  False    False   False     False   False  False  False
11  False  False    False   False     False   False  False  False
12  False  False    False   False     False   False  False  False
13  False  False    False   False     False   False  False  False
14  False  False    False   False     False   False  False  False
15  False  False    False   False     False   False  False  False
16  False  False    False   False     False   False  False  False
17  False  False    False   False     False   False  False  False
18  False  False     True   False     False   False  False  False
19  False  False    False   False     False   False  False  False

In [ ]:
df.notnull()

name  group  company  gender  birthday  height  blood  brand
0   True   True     True    True      True    True   True   True
1   True   True     True    True      True    True   True   True
2   True   True     True    True      True    True   True   True
3   True   True     True    True      True    True   True   True
4   True   True     True    True      True    True   True   True
5   True   True     True    True      True    True  False   True
6   True   True     True    True      True    True   True   True
7   True   True     True    True      True    True   True   True
8   True   True     True    True      True    True   True   True
9   True   True     True    True      True   False   True   True
10  True   True     True    True      True    True   True   True
11  True   True     True    True      True    True   True   True
12  True   True     True    True      True    True   True   True
13  True   True     True    True      True    True   True   True
14  True   True     True    True      True    True   True   True
15  True   True     True    True      True    True   True   True
16  True   True     True    True      True    True   True   True
17  True   True     True    True      True    True   True   True
18  True   True    False    True      True    True   True   True
19  True   True     True    True      True    True   True   True

In [ ]:
df['height'].isna()

# 0     False
# 1     False
# 2     False
# 3     False
# 4     False
# 5     False
# 6     False
# 7     False
# 8     False
# 9      True
# 10    False
# 11    False
# 12    False
# 13    False
# 14    False
# 15    False
# 16    False
# 17    False
# 18    False
# 19    False
# Name: height, dtype: bool

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: height, dtype: bool

In [ ]:
df[df['height'].isna()]

name group company gender    birthday  height blood    brand
9   태연  소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866

In [ ]:
# fillna(): 결측값을 채워주는 함수
df['height'].fillna(0) # df['height].fillna(0, inplace=True) 적용

# 0     174.0
# 1     179.0
# 2     169.0
# 3     161.7
# 4     179.0
# 5     165.0
# 6     170.0
# 7     162.0
# 8     164.5
# 9       0.0
# 10    181.0
# 11    163.0
# 12    179.0
# 13    167.0
# 14    168.0
# 15    168.0
# 16    168.0
# 17    161.0
# 18    182.0
# 19    179.0
# Name: height, dtype: float64

0     174.0
1     179.0
2     169.0
3     161.7
4     179.0
5     165.0
6     170.0
7     162.0
8     164.5
9       0.0
10    181.0
11    163.0
12    179.0
13    167.0
14    168.0
15    168.0
16    168.0
17    161.0
18    182.0
19    179.0
Name: height, dtype: float64

In [ ]:
df['height']
df_copy = df.copy()
df_copy

name  group company gender    birthday  height blood    brand
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587

In [ ]:
height = df_copy['height'].mean()
height

np.float64(170.53684210526316)

In [ ]:
height = df_copy['height'].mean()
df_copy['height'] = df_copy['height'].fillna(height)
df_copy['height']

# 0     174.000000
# 1     179.000000
# 2     169.000000
# 3     161.700000
# 4     179.000000
# 5     165.000000
# 6     170.000000
# 7     162.000000
# 8     164.500000
# 9     170.536842
# 10    181.000000
# 11    163.000000
# 12    179.000000
# 13    167.000000
# 14    168.000000
# 15    168.000000
# 16    168.000000
# 17    161.000000
# 18    182.000000
# 19    179.000000
# Name: height, dtype: float64


0     174.000000
1     179.000000
2     169.000000
3     161.700000
4     179.000000
5     165.000000
6     170.000000
7     162.000000
8     164.500000
9     170.536842
10    181.000000
11    163.000000
12    179.000000
13    167.000000
14    168.000000
15    168.000000
16    168.000000
17    161.000000
18    182.000000
19    179.000000
Name: height, dtype: float64

In [ ]:
height = df_copy['height'].median() # 50%값, 중위
height

np.float64(168.5)

In [ ]:
df_copy['height'].fillna(height, inplace=True)
df_copy['height']

0     174.000000
1     179.000000
2     169.000000
3     161.700000
4     179.000000
5     165.000000
6     170.000000
7     162.000000
8     164.500000
9     170.536842
10    181.000000
11    163.000000
12    179.000000
13    167.000000
14    168.000000
15    168.000000
16    168.000000
17    161.000000
18    182.000000
19    179.000000
Name: height, dtype: float64

In [ ]:
df_copy = df.copy()
df_copy

name  group company gender    birthday  height blood    brand
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587

In [ ]:
dic = {
    'name': '김사과',
    'group': '과수원',
    'company': '애플',
    'gender': '여자',
    'birthday': '2000-01-01',
    'height': 160.0,
    'blood': 'A',
    'brand': 1234567
}

# concat(): 데이터를 합침. axis=0 (기본값)
df_copy = pd.concat([df_copy, pd.DataFrame(dic, index=[0])], ignore_index=True)
df_copy.iloc[-1]

# name               김사과
# group              과수원
# company             애플
# gender              여자
# birthday    2000-01-01
# height           160.0
# blood                A
# brand          1234567
# Name: 25, dtype: object

name               김사과
group              과수원
company             애플
gender              여자
birthday    2000-01-01
height           160.0
blood                A
brand          1234567
Name: 25, dtype: object

In [ ]:
df_copy['nation'] = '대한민국'
df_copy.head()
# name	group	company	gender	birthday	height	blood	brand	nation
# 0	지민	방탄소년단	빅히트	남자	1995-10-13	174.0	A	6267302	대한민국
# 1	정국	방탄소년단	빅히트	남자	1997-09-01	179.0	A	5805844	대한민국

name  group company gender    birthday  height blood    brand nation
0   지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302   대한민국
1   정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844   대한민국
2   민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081   대한민국
3   하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153   대한민국
4    뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048   대한민국

In [ ]:
df_copy = df.copy()

In [ ]:
df_copy

name  group company gender    birthday  height blood    brand
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587

In [ ]:
# groupby(): 데이터를 그룹으로 묶어 분석할 때 사용
df_copy.groupby('group')

In [ ]:
# 그룹을 맺으면 통계함수를 사용할 수 있음
df_copy.groupby('group').count()

name  company  gender  birthday  height  blood  brand
group                                                       
뉴진스       5        5       5         5       5      4      5
레드벨벳      2        2       2         2       2      2      2
방탄소년단     5        5       5         5       5      5      5
블랙핑크      4        4       4         4       4      4      4
소녀시대      2        2       2         2       1      2      2
워너원       2        1       2         2       2      2      2

In [ ]:
df_copy.groupby('group').mean(numeric_only=True)

height      brand
group                   
뉴진스    166.04  3082933.2
레드벨벳   164.50  1786140.5
방탄소년단  178.40  3858656.0
블랙핑크   165.00  2024410.5
소녀시대   168.00  1982581.5
워너원    180.50  1830385.5

In [ ]:
df_copy.groupby(['blood','gender']).mean(numeric_only=True)

height         brand
blood gender                       
A     남자      179.000  3.560683e+06
      여자      165.400  2.371581e+06
AB    남자      179.000  3.470048e+06
B     여자      165.875  2.004014e+06
O     남자      179.000  1.680587e+06
      여자      165.850  3.231469e+06

In [ ]:
df_copy['blood'].drop_duplicates(keep='last')

# 4      AB
# 5     NaN
# 15      B
# 18      A
# 19      O
# Name: blood, dtype: object

4      AB
5     NaN
15      B
18      A
19      O
Name: blood, dtype: object

In [ ]:
df_copy['company'].value_counts()

# company
# 빅히트     7
# 어도어     5
# 와이지     4
# 에스엠     2
# 판타지오    1
# Name: count, dtype: int64

company
빅히트     7
어도어     5
와이지     4
에스엠     2
판타지오    1
Name: count, dtype: int64

In [ ]:
df_copy['company'].value_counts(dropna=False) # NaN를 포함

company
빅히트     7
어도어     5
와이지     4
에스엠     2
판타지오    1
NaN     1
Name: count, dtype: int64

In [ ]:
df1 = pd.read_csv('idol.csv')
df2 = pd.read_csv('idol2.csv')

df2

이름    연봉  가족수
0     지민  3000    3
1     정국  3500    3
2     민지  3200    4
3     하니  3050    4
4      뷔  4300    3
5    다니엘  2900    5
6     혜인  3400    6
7     지수  4500    5
8     해린  4200    4
9     태연  4300    4
10    RM  3700    3
11    제니  3850    5
12   옹성우  3900    4
13    리사  4100    3
14    로제  4150    3
15    윤아  3000    3
16    조이  3500    3
17    슬기  3200    4
18  강다니엘  3050    4
19     진  4300    3

In [ ]:
df_copy = df1.copy()

In [ ]:
pd.concat([df1, df_copy])

이름     그룹   소속사  성별        생년월일      키  혈액형  브랜드평판지수
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587

In [ ]:
df_concat = pd.concat([df1, df_copy])

# reset_index(): index를 새롭게 적용
# drop=True 옵션을 사용하여 기존 index가 컬럼으로 만들어지는 것을 방지
df_concat.reset_index(drop=True)

이름     그룹   소속사  성별        생년월일      키  혈액형  브랜드평판지수
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587
20    지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302
21    정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844
22    민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081
23    하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153
24     뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048
25   다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271
26    혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785
27    지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460
28    해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376
29    태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866
30    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499
31    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250
32   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327
33    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800
34    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132
35    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297
36    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514
37    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767
38  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444
39     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587

In [ ]:
pd.concat([df1, df2], axis=1) # 같은 index와 결합

이름     그룹   소속사  성별        생년월일      키  혈액형  브랜드평판지수    이름    연봉  가족수
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302    지민  3000    3
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844    정국  3500    3
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081    민지  3200    4
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153    하니  3050    4
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048     뷔  4300    3
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271   다니엘  2900    5
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785    혜인  3400    6
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460    지수  4500    5
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376    해린  4200    4
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866    태연  4300    4
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499    RM  3700    3
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250    제니  3850    5
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327   옹성우  3900    4
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800    리사  4100    3
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132    로제  4150    3
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297    윤아  3000    3
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514    조이  3500    3
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767    슬기  3200    4
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444  강다니엘  3050    4
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587     진  4300    3

In [ ]:
df3 = df2.drop([1, 3, 5, 7, 9])
df3

이름    연봉  가족수
0     지민  3000    3
2     민지  3200    4
4      뷔  4300    3
6     혜인  3400    6
8     해린  4200    4
10    RM  3700    3
11    제니  3850    5
12   옹성우  3900    4
13    리사  4100    3
14    로제  4150    3
15    윤아  3000    3
16    조이  3500    3
17    슬기  3200    4
18  강다니엘  3050    4
19     진  4300    3

In [ ]:
pd.concat([df1, df3], axis=1)

이름     그룹   소속사  성별        생년월일      키  혈액형  브랜드평판지수    이름      연봉  가족수
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302    지민  3000.0  3.0
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844   NaN     NaN  NaN
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081    민지  3200.0  4.0
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153   NaN     NaN  NaN
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048     뷔  4300.0  3.0
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271   NaN     NaN  NaN
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785    혜인  3400.0  6.0
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460   NaN     NaN  NaN
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376    해린  4200.0  4.0
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866   NaN     NaN  NaN
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499    RM  3700.0  3.0
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250    제니  3850.0  5.0
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327   옹성우  3900.0  4.0
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800    리사  4100.0  3.0
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132    로제  4150.0  3.0
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297    윤아  3000.0  3.0
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514    조이  3500.0  3.0
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767    슬기  3200.0  4.0
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444  강다니엘  3050.0  4.0
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587     진  4300.0  3.0

In [ ]:
df_right = df2.drop([1, 3, 5, 7, 9], axis=0)
df_right

이름    연봉  가족수
0     지민  3000    3
2     민지  3200    4
4      뷔  4300    3
6     혜인  3400    6
8     해린  4200    4
10    RM  3700    3
11    제니  3850    5
12   옹성우  3900    4
13    리사  4100    3
14    로제  4150    3
15    윤아  3000    3
16    조이  3500    3
17    슬기  3200    4
18  강다니엘  3050    4
19     진  4300    3

In [ ]:
df_right = df_right.reset_index(drop=True)
df_right

이름      연봉  가족수 name group company gender    birthday  height blood  \
0     지민  3000.0  3.0  NaN   NaN     NaN    NaN         NaN     NaN   NaN   
1     민지  3200.0  4.0  NaN   NaN     NaN    NaN         NaN     NaN   NaN   
2      뷔  4300.0  3.0  NaN   NaN     NaN    NaN         NaN     NaN   NaN   
3     혜인  3400.0  6.0  NaN   NaN     NaN    NaN         NaN     NaN   NaN   
4     해린  4200.0  4.0  NaN   NaN     NaN    NaN         NaN     NaN   NaN   
5     RM  3700.0  3.0  NaN   NaN     NaN    NaN         NaN     NaN   NaN   
6     제니  3850.0  5.0  NaN   NaN     NaN    NaN         NaN     NaN   NaN   
7    옹성우  3900.0  4.0  NaN   NaN     NaN    NaN         NaN     NaN   NaN   
8     리사  4100.0  3.0  NaN   NaN     NaN    NaN         NaN     NaN   NaN   
9     로제  4150.0  3.0  NaN   NaN     NaN    NaN         NaN     NaN   NaN   
10    윤아  3000.0  3.0  NaN   NaN     NaN    NaN         NaN     NaN   NaN   
11    조이  3500.0  3.0  NaN   NaN     NaN    NaN         NaN     NaN   NaN   
12    슬기  3200.0  4.0  NaN   NaN     NaN    NaN         NaN     NaN   NaN   
13  강다니엘  3050.0  4.0  NaN   NaN     NaN    NaN         NaN     NaN   NaN   
14     진  4300.0  3.0  NaN   NaN     NaN    NaN         NaN     NaN   NaN   
15   NaN     NaN  NaN  김사과   과수원      애플     여자  2000-01-01   160.0     A   

        brand  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
4         NaN  
5         NaN  
6         NaN  
7         NaN  
8         NaN  
9         NaN  
10        NaN  
11        NaN  
12        NaN  
13        NaN  
14        NaN  
15  1234567.0

In [ ]:
pd.concat([df1, df_right], axis=1)

이름     그룹   소속사  성별        생년월일      키  혈액형  브랜드평판지수    이름      연봉  가족수  \
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302    지민  3000.0  3.0   
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844    민지  3200.0  4.0   
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081     뷔  4300.0  3.0   
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153    혜인  3400.0  6.0   
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048    해린  4200.0  4.0   
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271    RM  3700.0  3.0   
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785    제니  3850.0  5.0   
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460   옹성우  3900.0  4.0   
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376    리사  4100.0  3.0   
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866    로제  4150.0  3.0   
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499    윤아  3000.0  3.0   
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250    조이  3500.0  3.0   
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327    슬기  3200.0  4.0   
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800  강다니엘  3050.0  4.0   
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132     진  4300.0  3.0   
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297   NaN     NaN  NaN   
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514   NaN     NaN  NaN   
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767   NaN     NaN  NaN   
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444   NaN     NaN  NaN   
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587   NaN     NaN  NaN   

   name group company gender    birthday  height blood      brand  
0   NaN   NaN     NaN    NaN         NaN     NaN   NaN        NaN  
1   NaN   NaN     NaN    NaN         NaN     NaN   NaN        NaN  
2   NaN   NaN     NaN    NaN         NaN     NaN   NaN        NaN  
3   NaN   NaN     NaN    NaN         NaN     NaN   NaN        NaN  
4   NaN   NaN     NaN    NaN         NaN     NaN   NaN        NaN  
5   NaN   NaN     NaN    NaN         NaN     NaN   NaN        NaN  
6   NaN   NaN     NaN    NaN         NaN     NaN   NaN        NaN  
7   NaN   NaN     NaN    NaN         NaN     NaN   NaN        NaN  
8   NaN   NaN     NaN    NaN         NaN     NaN   NaN        NaN  
9   NaN   NaN     NaN    NaN         NaN     NaN   NaN        NaN  
10  NaN   NaN     NaN    NaN         NaN     NaN   NaN        NaN  
11  NaN   NaN     NaN    NaN         NaN     NaN   NaN        NaN  
12  NaN   NaN     NaN    NaN         NaN     NaN   NaN        NaN  
13  NaN   NaN     NaN    NaN         NaN     NaN   NaN        NaN  
14  NaN   NaN     NaN    NaN         NaN     NaN   NaN        NaN  
15  김사과   과수원      애플     여자  2000-01-01   160.0     A  1234567.0  
16  NaN   NaN     NaN    NaN         NaN     NaN   NaN        NaN  
17  NaN   NaN     NaN    NaN         NaN     NaN   NaN        NaN  
18  NaN   NaN     NaN    NaN         NaN     NaN   NaN        NaN  
19  NaN   NaN     NaN    NaN         NaN     NaN   NaN        NaN

In [ ]:
df1 = pd.read_csv('idol.csv')

# merge(): 특정 고유한 키(unique, id)값을 기준으로 합침
# merge(데이터프레임1, 데이터프레임2, on='유니크값', how='병합의 기준')
# 병합의 기준: left, right, inner, cross
pd.merge(df1, df_right, on='이름', how='inner')

이름     그룹   소속사  성별        생년월일      키 혈액형  브랜드평판지수      연봉  가족수 name  \
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0   A  6267302  3000.0  3.0  NaN   
1     민지    뉴진스   어도어  여자  2004-05-07  169.0   A  4437081  3200.0  4.0  NaN   
2      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0  AB  3470048  4300.0  3.0  NaN   
3     혜인    뉴진스   어도어  여자  2008-04-21  170.0   O  2301785  3400.0  6.0  NaN   
4     해린    뉴진스   어도어  여자  2006-05-15  164.5   B  2173376  4200.0  4.0  NaN   
5     RM  방탄소년단   빅히트  남자  1994-09-12  181.0   A  2069499  3700.0  3.0  NaN   
6     제니   블랙핑크   와이지  여자  1996-01-16  163.0   B  2069250  3850.0  5.0  NaN   
7    옹성우    워너원  판타지오  남자  1995-08-25  179.0   A  1954327  3900.0  4.0  NaN   
8     리사   블랙핑크   와이지  여자  1997-03-27  167.0   A  1912800  4100.0  3.0  NaN   
9     로제   블랙핑크   와이지  여자  1997-02-11  168.0   B  1888132  4150.0  3.0  NaN   
10    윤아   소녀시대   에스엠  여자  1990-05-30  168.0   B  1885297  3000.0  3.0  NaN   
11    조이   레드벨벳   빅히트  여자  1996-09-03  168.0   A  1830514  3500.0  3.0  NaN   
12    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0   A  1741767  3200.0  4.0  NaN   
13  강다니엘    워너원   NaN  남자  1996-12-10  182.0   A  1706444  3050.0  4.0  NaN   
14     진  방탄소년단   빅히트  남자  1992-12-04  179.0   O  1680587  4300.0  3.0  NaN   

   group company gender birthday  height blood  brand  
0    NaN     NaN    NaN      NaN     NaN   NaN    NaN  
1    NaN     NaN    NaN      NaN     NaN   NaN    NaN  
2    NaN     NaN    NaN      NaN     NaN   NaN    NaN  
3    NaN     NaN    NaN      NaN     NaN   NaN    NaN  
4    NaN     NaN    NaN      NaN     NaN   NaN    NaN  
5    NaN     NaN    NaN      NaN     NaN   NaN    NaN  
6    NaN     NaN    NaN      NaN     NaN   NaN    NaN  
7    NaN     NaN    NaN      NaN     NaN   NaN    NaN  
8    NaN     NaN    NaN      NaN     NaN   NaN    NaN  
9    NaN     NaN    NaN      NaN     NaN   NaN    NaN  
10   NaN     NaN    NaN      NaN     NaN   NaN    NaN  
11   NaN     NaN    NaN      NaN     NaN   NaN    NaN  
12   NaN     NaN    NaN      NaN     NaN   NaN    NaN  
13   NaN     NaN    NaN      NaN     NaN   NaN    NaN  
14   NaN     NaN    NaN      NaN     NaN   NaN    NaN

In [ ]:
# rank(): 데이터프레임 또는 시리즈의 순위를 매기는 함수. 기본값은 ascending
df1['브랜드순위'] = df1['브랜드평판지수'].rank()
df1

이름     그룹   소속사  성별        생년월일      키  혈액형  브랜드평판지수  브랜드순위
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302   20.0
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844   19.0
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081   18.0
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153   17.0
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048   16.0
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271   15.0
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785   14.0
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460   13.0
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376   12.0
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866   11.0
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499   10.0
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250    9.0
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327    8.0
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800    7.0
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132    6.0
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297    5.0
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514    4.0
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767    3.0
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444    2.0
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587    1.0

In [ ]:
df_copy = df.copy()
df_copy

name  group company gender    birthday  height blood    brand
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587

In [ ]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      20 non-null     object 
 1   group     20 non-null     object 
 2   company   19 non-null     object 
 3   gender    20 non-null     object 
 4   birthday  20 non-null     object 
 5   height    19 non-null     float64
 6   blood     19 non-null     object 
 7   brand     20 non-null     int64  
dtypes: float64(1), int64(1), object(6)
memory usage: 1.4+ KB


In [ ]:
df_copy.info()['birthday']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      20 non-null     object 
 1   group     20 non-null     object 
 2   company   19 non-null     object 
 3   gender    20 non-null     object 
 4   birthday  20 non-null     object 
 5   height    19 non-null     float64
 6   blood     19 non-null     object 
 7   brand     20 non-null     int64  
dtypes: float64(1), int64(1), object(6)
memory usage: 1.4+ KB


TypeError: 'NoneType' object is not subscriptable

In [ ]:
# to_datatime(): object타입에서 datetime타입으로 변환
df_copy['birthday'] = pd.to_datetime(df_copy['birthday'])
print(type(df_copy['birthday']))
print(df_copy['birthday'].dtypes)

<class 'pandas.core.series.Series'>
datetime64[ns]


In [ ]:
df_copy['birthday'].dt.year

0     1995
1     1997
2     2004
3     2004
4     1995
5     2005
6     2008
7     1995
8     2006
9     1989
10    1994
11    1996
12    1995
13    1997
14    1997
15    1990
16    1996
17    1994
18    1996
19    1992
Name: birthday, dtype: int32

In [ ]:
df_copy['birthday'].dt.isocalendar().week

0     41
1     36
2     19
3     41
4     52
5     15
6     17
7      1
8     20
9     10
10    37
11     3
12    34
13    13
14     7
15    22
16    36
17     6
18    50
19    49
Name: week, dtype: UInt32

In [ ]:
def male_or_female(x):
    if x == '남자':
        return 1
    elif x == '여자':
        return 0
    else:
        return None

df_copy['gender'].apply(male_or_female)

# 0     1
# 1     1
# 2     0
# 3     0
# 4     1
# 5     0
# 6     0
# 7     0
# 8     0
# 9     0
# 10    1
# 11    0
# 12    1
# 13    0
# 14    0
# 15    0
# 16    0
# 17    0
# 18    1
# 19    1
# Name: gender, dtype: int64


0     1
1     1
2     0
3     0
4     1
5     0
6     0
7     0
8     0
9     0
10    1
11    0
12    1
13    0
14    0
15    0
16    0
17    0
18    1
19    1
Name: gender, dtype: int64

In [ ]:
df_copy['gender'].apply(lambda x: 1 if x == '남자' else 0 if x == '여자' else None)

0     1
1     1
2     0
3     0
4     1
5     0
6     0
7     0
8     0
9     0
10    1
11    0
12    1
13    0
14    0
15    0
16    0
17    0
18    1
19    1
Name: gender, dtype: int64

In [ ]:
map_gender = {'남자':1, '여자':0}

df_copy['gender'].map(map_gender)

# 0     1
# 1     1
# 2     0
# 3     0
# 4     1
# 5     0
# 6     0
# 7     0
# 8     0
# 9     0
# 10    1
# 11    0
# 12    1
# 13    0
# 14    0
# 15    0
# 16    0
# 17    0
# 18    1
# 19    1
# Name: gender, dtype: int64

0     1
1     1
2     0
3     0
4     1
5     0
6     0
7     0
8     0
9     0
10    1
11    0
12    1
13    0
14    0
15    0
16    0
17    0
18    1
19    1
Name: gender, dtype: int64

In [ ]:
df1 = pd.DataFrame({
    '파이썬':[60, 70, 80, 90, 95],
    '데이터분석':[40, 60, 70, 55, 87],
    '머신러닝딥러닝':[35, 40, 30, 70, 55]
})
total = df1['파이썬'] + df1['데이터분석'] + df1['머신러닝딥러닝']

# 0    135
# 1    170
# 2    180
# 3    215
# 4    237
# dtype: int64

0    135
1    170
2    180
3    215
4    237
dtype: int64

In [3]:
!pip install pandas
!pip install numpy

     ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
     - -------------------------------------- 0.4/11.3 MB 13.9 MB/s eta 0:00:01
     --- ------------------------------------ 0.9/11.3 MB 13.7 MB/s eta 0:00:01
     ---- ----------------------------------- 1.3/11.3 MB 14.1 MB/s eta 0:00:01
     ------ --------------------------------- 1.8/11.3 MB 12.5 MB/s eta 0:00:01
     ------- -------------------------------- 2.2/11.3 MB 12.8 MB/s eta 0:00:01
     --------- ------------------------------ 2.6/11.3 MB 12.9 MB/s eta 0:00:01
     ---------- ----------------------------- 3.1/11.3 MB 13.0 MB/s eta 0:00:01
     ------------ --------------------------- 3.5/11.3 MB 12.4 MB/s eta 0:00:01
     ------------- -------------------------- 3.9/11.3 MB 12.6 MB/s eta 0:00:01
     --------------- ------------------------ 4.4/11.3 MB 12.7 MB/s eta 0:00:01
     ----------------- ---------------------- 4.8/11.3 MB 12.4 MB/s eta 0:00:01
     ------------------ --------------------- 5.


[notice] A new release of pip is available: 23.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 23.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [11]:
import pandas as pd

df = pd.read_csv('idol.csv')

In [ ]:
df = pd.get_dummies(df, columns=['혈액형'])


KeyError: "None of [Index(['혈액형'], dtype='object')] are in the [columns]"

In [12]:
df

이름     그룹   소속사  성별        생년월일      키  혈액형  브랜드평판지수
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587